include: package:lint/analysis_options_package.yaml
analyzer:
    exclude:
        - lib/ffi.dart
        - "**/*.g.dart"
        - "**/*.pb.dart"
        - "**/*.pbjson.dart"
        - "**/*.pbenum.dart"
        - "**/*.pbgrpc.dart"

